create sequence cidade_id_seq start 1 increment 1;
create sequence cozinha_id_seq start 1 increment 1;
create sequence estado_id_seq start 1 increment 1;
create sequence forma_pagamento_id_seq start 1 increment 1;
create sequence grupo_id_seq start 1 increment 1;
create sequence permissao_id_seq start 1 increment 1;
create sequence produto_id_seq start 1 increment 1;
create sequence restaurante_id_seq start 1 increment 1;
create table cidade (id int8 not null, nome varchar(255) not null, estado_id int8 not null, primary key (id));
create table cozinha (id int8 not null, nome varchar(255) not null, primary key (id));
create table estado (id int8 not null, nome varchar(255) not null, sigla varchar(255) not null, primary key (id));
create table forma_pagamento (id int8 not null, descricao varchar(255) not null, primary key (id));
create table grupo (id int8 not null, nome varchar(255) not null, primary key (id));
create table grupo_has_permissao (grupo_id int8 not null, permissao_id int8 not null);
create table permissao (id int8 not null, descricao varchar(255), nome varchar(255) not null, primary key (id));
create table produto (id int8 not null, ativo boolean not null, descricao varchar(255), nome varchar(255) not null, preco numeric(19, 2) not null, restaurante_id int8, primary key (id));
create table restaurante (id int8 not null, created_at timestamp not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19, 2) not null, updated_at timestamp not null, cozinha_id int8 not null, endereco_cidade_id int8, primary key (id));
create table restaurante_has_forma_pagamento (restaurante_id int8 not null, forma_pagamento_id int8 not null);
create table usuario (id int8 not null, created_at timestamp not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, updated_at timestamp not null, primary key (id));
create table usuario_grupo (usuario_id int8 not null, grupo_id int8 not null);
alter table if exists cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado;
alter table if exists grupo_has_permissao add constraint FK4yy0qdocy8v7nslsu7lx1mmyk foreign key (permissao_id) references permissao;
alter table if exists grupo_has_permissao add constraint FKibwh6sgnrbw6nun3e13aoqygp foreign key (grupo_id) references grupo;
alter table if exists produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante;
alter table if exists restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha;
alter table if exists restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade;
alter table if exists restaurante_has_forma_pagamento add constraint FKh8mrqys0q1j1dw5jpankl6jn0 foreign key (forma_pagamento_id) references forma_pagamento;
alter table if exists restaurante_has_forma_pagamento add constraint FK3d8qb62mp0mi0rw16djsnspjg foreign key (restaurante_id) references restaurante;
alter table if exists usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo;
alter table if exists usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario;
create sequence cidade_id_seq start 1 increment 1;
create sequence cozinha_id_seq start 1 increment 1;
create sequence estado_id_seq start 1 increment 1;
create sequence forma_pagamento_id_seq start 1 increment 1;
create sequence grupo_id_seq start 1 increment 1;
create sequence permissao_id_seq start 1 increment 1;
create sequence produto_id_seq start 1 increment 1;
create sequence restaurante_id_seq start 1 increment 1;
create table cidade (id int8 not null, nome varchar(255) not null, estado_id int8 not null, primary key (id));
create table cozinha (id int8 not null, nome varchar(255) not null, primary key (id));
create table estado (id int8 not null, nome varchar(255) not null, sigla varchar(255) not null, primary key (id));
create table forma_pagamento (id int8 not null, descricao varchar(255) not null, primary key (id));
create table grupo (id int8 not null, nome varchar(255) not null, primary key (id));
create table grupo_has_permissao (grupo_id int8 not null, permissao_id int8 not null);
create table permissao (id int8 not null, descricao varchar(255), nome varchar(255) not null, primary key (id));
create table produto (id int8 not null, ativo boolean not null, descricao varchar(255), nome varchar(255) not null, preco numeric(19, 2) not null, restaurante_id int8, primary key (id));
create table restaurante (id int8 not null, created_at timestamp not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19, 2) not null, updated_at timestamp not null, cozinha_id int8 not null, endereco_cidade_id int8, primary key (id));
create table restaurante_has_forma_pagamento (restaurante_id int8 not null, forma_pagamento_id int8 not null);
create table usuario (id int8 not null, created_at timestamp not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, updated_at timestamp not null, primary key (id));
create table usuario_grupo (usuario_id int8 not null, grupo_id int8 not null);
alter table if exists cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado;
alter table if exists grupo_has_permissao add constraint FK4yy0qdocy8v7nslsu7lx1mmyk foreign key (permissao_id) references permissao;
alter table if exists grupo_has_permissao add constraint FKibwh6sgnrbw6nun3e13aoqygp foreign key (grupo_id) references grupo;
alter table if exists produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante;
alter table if exists restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha;
alter table if exists restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade;
alter table if exists restaurante_has_forma_pagamento add constraint FKh8mrqys0q1j1dw5jpankl6jn0 foreign key (forma_pagamento_id) references forma_pagamento;
alter table if exists restaurante_has_forma_pagamento add constraint FK3d8qb62mp0mi0rw16djsnspjg foreign key (restaurante_id) references restaurante;
alter table if exists usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo;
alter table if exists usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario;
create sequence cidade_id_seq start 1 increment 1;
create sequence cozinha_id_seq start 1 increment 1;
create sequence estado_id_seq start 1 increment 1;
create sequence forma_pagamento_id_seq start 1 increment 1;
create sequence grupo_id_seq start 1 increment 1;
create sequence permissao_id_seq start 1 increment 1;
create sequence produto_id_seq start 1 increment 1;
create sequence restaurante_id_seq start 1 increment 1;
create table cidade (id int8 not null, nome varchar(255) not null, estado_id int8 not null, primary key (id));
create table cozinha (id int8 not null, nome varchar(255) not null, primary key (id));
create table estado (id int8 not null, nome varchar(255) not null, sigla varchar(255) not null, primary key (id));
create table forma_pagamento (id int8 not null, descricao varchar(255) not null, primary key (id));
create table grupo (id int8 not null, nome varchar(255) not null, primary key (id));
create table grupo_has_permissao (grupo_id int8 not null, permissao_id int8 not null);
create table permissao (id int8 not null, descricao varchar(255), nome varchar(255) not null, primary key (id));
create table produto (id int8 not null, ativo boolean not null, descricao varchar(255), nome varchar(255) not null, preco numeric(19, 2) not null, restaurante_id int8, primary key (id));
create table restaurante (id int8 not null, created_at timestamp not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19, 2) not null, updated_at timestamp not null, cozinha_id int8 not null, endereco_cidade_id int8, primary key (id));
create table restaurante_has_forma_pagamento (restaurante_id int8 not null, forma_pagamento_id int8 not null);
create table usuario (id int8 not null, created_at timestamp not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, updated_at timestamp not null, primary key (id));
create table usuario_grupo (usuario_id int8 not null, grupo_id int8 not null);
alter table if exists cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado;
alter table if exists grupo_has_permissao add constraint FK4yy0qdocy8v7nslsu7lx1mmyk foreign key (permissao_id) references permissao;
alter table if exists grupo_has_permissao add constraint FKibwh6sgnrbw6nun3e13aoqygp foreign key (grupo_id) references grupo;
alter table if exists produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante;
alter table if exists restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha;
alter table if exists restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade;
alter table if exists restaurante_has_forma_pagamento add constraint FKh8mrqys0q1j1dw5jpankl6jn0 foreign key (forma_pagamento_id) references forma_pagamento;
alter table if exists restaurante_has_forma_pagamento add constraint FK3d8qb62mp0mi0rw16djsnspjg foreign key (restaurante_id) references restaurante;
alter table if exists usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo;
alter table if exists usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario;
create sequence cidade_id_seq start 1 increment 1;
create sequence cozinha_id_seq start 1 increment 1;
create sequence estado_id_seq start 1 increment 1;
create sequence forma_pagamento_id_seq start 1 increment 1;
create sequence grupo_id_seq start 1 increment 1;
create sequence permissao_id_seq start 1 increment 1;
create sequence produto_id_seq start 1 increment 1;
create sequence restaurante_id_seq start 1 increment 1;
create table cidade (id int8 not null, nome varchar(255) not null, estado_id int8 not null, primary key (id));
create table cozinha (id int8 not null, nome varchar(255) not null, primary key (id));
create table estado (id int8 not null, nome varchar(255) not null, sigla varchar(255) not null, primary key (id));
create table forma_pagamento (id int8 not null, descricao varchar(255) not null, primary key (id));
create table grupo (id int8 not null, nome varchar(255) not null, primary key (id));
create table grupo_has_permissao (grupo_id int8 not null, permissao_id int8 not null);
create table permissao (id int8 not null, descricao varchar(255), nome varchar(255) not null, primary key (id));
create table produto (id int8 not null, ativo boolean not null, descricao varchar(255), nome varchar(255) not null, preco numeric(19, 2) not null, restaurante_id int8, primary key (id));
create table restaurante (id int8 not null, created_at timestamp not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19, 2) not null, updated_at timestamp not null, cozinha_id int8 not null, endereco_cidade_id int8, primary key (id));
create table restaurante_has_forma_pagamento (restaurante_id int8 not null, forma_pagamento_id int8 not null);
create table usuario (id int8 not null, created_at timestamp not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, updated_at timestamp not null, primary key (id));
create table usuario_grupo (usuario_id int8 not null, grupo_id int8 not null);
alter table if exists cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado;
alter table if exists grupo_has_permissao add constraint FK4yy0qdocy8v7nslsu7lx1mmyk foreign key (permissao_id) references permissao;
alter table if exists grupo_has_permissao add constraint FKibwh6sgnrbw6nun3e13aoqygp foreign key (grupo_id) references grupo;
alter table if exists produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante;
alter table if exists restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha;
alter table if exists restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade;
alter table if exists restaurante_has_forma_pagamento add constraint FKh8mrqys0q1j1dw5jpankl6jn0 foreign key (forma_pagamento_id) references forma_pagamento;
alter table if exists restaurante_has_forma_pagamento add constraint FK3d8qb62mp0mi0rw16djsnspjg foreign key (restaurante_id) references restaurante;
alter table if exists usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo;
alter table if exists usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario;
create sequence cidade_id_seq start 1 increment 1;
create sequence cozinha_id_seq start 1 increment 1;
create sequence estado_id_seq start 1 increment 1;
create sequence forma_pagamento_id_seq start 1 increment 1;
create sequence grupo_id_seq start 1 increment 1;
create sequence permissao_id_seq start 1 increment 1;
create sequence produto_id_seq start 1 increment 1;
create sequence restaurante_id_seq start 1 increment 1;
create table cidade (id int8 not null, nome varchar(255) not null, estado_id int8 not null, primary key (id));
create table cozinha (id int8 not null, nome varchar(255) not null, primary key (id));
create table estado (id int8 not null, nome varchar(255) not null, sigla varchar(255) not null, primary key (id));
create table forma_pagamento (id int8 not null, descricao varchar(255) not null, primary key (id));
create table grupo (id int8 not null, nome varchar(255) not null, primary key (id));
create table grupo_has_permissao (grupo_id int8 not null, permissao_id int8 not null);
create table permissao (id int8 not null, descricao varchar(255), nome varchar(255) not null, primary key (id));
create table produto (id int8 not null, ativo boolean not null, descricao varchar(255), nome varchar(255) not null, preco numeric(19, 2) not null, restaurante_id int8, primary key (id));
create table restaurante (id int8 not null, created_at timestamp not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19, 2) not null, updated_at timestamp not null, cozinha_id int8 not null, endereco_cidade_id int8, primary key (id));
create table restaurante_has_forma_pagamento (restaurante_id int8 not null, forma_pagamento_id int8 not null);
create table usuario (id int8 not null, created_at timestamp not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, updated_at timestamp not null, primary key (id));
create table usuario_grupo (usuario_id int8 not null, grupo_id int8 not null);
alter table if exists cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado;
alter table if exists grupo_has_permissao add constraint FK4yy0qdocy8v7nslsu7lx1mmyk foreign key (permissao_id) references permissao;
alter table if exists grupo_has_permissao add constraint FKibwh6sgnrbw6nun3e13aoqygp foreign key (grupo_id) references grupo;
alter table if exists produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante;
alter table if exists restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha;
alter table if exists restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade;
alter table if exists restaurante_has_forma_pagamento add constraint FKh8mrqys0q1j1dw5jpankl6jn0 foreign key (forma_pagamento_id) references forma_pagamento;
alter table if exists restaurante_has_forma_pagamento add constraint FK3d8qb62mp0mi0rw16djsnspjg foreign key (restaurante_id) references restaurante;
alter table if exists usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo;
alter table if exists usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario;
create sequence cidade_id_seq start 1 increment 1;
create sequence cozinha_id_seq start 1 increment 1;
create sequence estado_id_seq start 1 increment 1;
create sequence forma_pagamento_id_seq start 1 increment 1;
create sequence grupo_id_seq start 1 increment 1;
create sequence permissao_id_seq start 1 increment 1;
create sequence produto_id_seq start 1 increment 1;
create sequence restaurante_id_seq start 1 increment 1;
create table cidade (id int8 not null, nome varchar(255) not null, estado_id int8 not null, primary key (id));
create table cozinha (id int8 not null, nome varchar(255) not null, primary key (id));
create table estado (id int8 not null, nome varchar(255) not null, sigla varchar(255) not null, primary key (id));
create table forma_pagamento (id int8 not null, descricao varchar(255) not null, primary key (id));
create table grupo (id int8 not null, nome varchar(255) not null, primary key (id));
create table grupo_has_permissao (grupo_id int8 not null, permissao_id int8 not null);
create table permissao (id int8 not null, descricao varchar(255), nome varchar(255) not null, primary key (id));
create table produto (id int8 not null, ativo boolean not null, descricao varchar(255), nome varchar(255) not null, preco numeric(19, 2) not null, restaurante_id int8, primary key (id));
create table restaurante (id int8 not null, created_at timestamp not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19, 2) not null, updated_at timestamp not null, cozinha_id int8 not null, endereco_cidade_id int8, primary key (id));
create table restaurante_has_forma_pagamento (restaurante_id int8 not null, forma_pagamento_id int8 not null);
create table usuario (id int8 not null, created_at timestamp not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, updated_at timestamp not null, primary key (id));
create table usuario_grupo (usuario_id int8 not null, grupo_id int8 not null);
alter table if exists cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado;
alter table if exists grupo_has_permissao add constraint FK4yy0qdocy8v7nslsu7lx1mmyk foreign key (permissao_id) references permissao;
alter table if exists grupo_has_permissao add constraint FKibwh6sgnrbw6nun3e13aoqygp foreign key (grupo_id) references grupo;
alter table if exists produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante;
alter table if exists restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha;
alter table if exists restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade;
alter table if exists restaurante_has_forma_pagamento add constraint FKh8mrqys0q1j1dw5jpankl6jn0 foreign key (forma_pagamento_id) references forma_pagamento;
alter table if exists restaurante_has_forma_pagamento add constraint FK3d8qb62mp0mi0rw16djsnspjg foreign key (restaurante_id) references restaurante;
alter table if exists usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo;
alter table if exists usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario;
create sequence cidade_id_seq start 1 increment 1;
create sequence cozinha_id_seq start 1 increment 1;
create sequence estado_id_seq start 1 increment 1;
create sequence forma_pagamento_id_seq start 1 increment 1;
create sequence grupo_id_seq start 1 increment 1;
create sequence permissao_id_seq start 1 increment 1;
create sequence produto_id_seq start 1 increment 1;
create sequence restaurante_id_seq start 1 increment 1;
create table cidade (id int8 not null, nome varchar(255) not null, estado_id int8 not null, primary key (id));
create table cozinha (id int8 not null, nome varchar(255) not null, primary key (id));
create table estado (id int8 not null, nome varchar(255) not null, sigla varchar(255) not null, primary key (id));
create table forma_pagamento (id int8 not null, descricao varchar(255) not null, primary key (id));
create table grupo (id int8 not null, nome varchar(255) not null, primary key (id));
create table grupo_has_permissao (grupo_id int8 not null, permissao_id int8 not null);
create table permissao (id int8 not null, descricao varchar(255), nome varchar(255) not null, primary key (id));
create table produto (id int8 not null, ativo boolean not null, descricao varchar(255), nome varchar(255) not null, preco numeric(19, 2) not null, restaurante_id int8, primary key (id));
create table restaurante (id int8 not null, created_at timestamp not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19, 2) not null, updated_at timestamp not null, cozinha_id int8 not null, endereco_cidade_id int8, primary key (id));
create table restaurante_has_forma_pagamento (restaurante_id int8 not null, forma_pagamento_id int8 not null);
create table usuario (id int8 not null, created_at timestamp not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, updated_at timestamp not null, primary key (id));
create table usuario_grupo (usuario_id int8 not null, grupo_id int8 not null);
alter table if exists cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado;
alter table if exists grupo_has_permissao add constraint FK4yy0qdocy8v7nslsu7lx1mmyk foreign key (permissao_id) references permissao;
alter table if exists grupo_has_permissao add constraint FKibwh6sgnrbw6nun3e13aoqygp foreign key (grupo_id) references grupo;
alter table if exists produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante;
alter table if exists restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha;
alter table if exists restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade;
alter table if exists restaurante_has_forma_pagamento add constraint FKh8mrqys0q1j1dw5jpankl6jn0 foreign key (forma_pagamento_id) references forma_pagamento;
alter table if exists restaurante_has_forma_pagamento add constraint FK3d8qb62mp0mi0rw16djsnspjg foreign key (restaurante_id) references restaurante;
alter table if exists usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo;
alter table if exists usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario;
create sequence cidade_id_seq start 1 increment 1;
create sequence cozinha_id_seq start 1 increment 1;
create sequence estado_id_seq start 1 increment 1;
create sequence forma_pagamento_id_seq start 1 increment 1;
create sequence grupo_id_seq start 1 increment 1;
create sequence permissao_id_seq start 1 increment 1;
create sequence produto_id_seq start 1 increment 1;
create sequence restaurante_id_seq start 1 increment 1;
create table cidade (id int8 not null, nome varchar(255) not null, estado_id int8 not null, primary key (id));
create table cozinha (id int8 not null, nome varchar(255) not null, primary key (id));
create table estado (id int8 not null, nome varchar(255) not null, sigla varchar(255) not null, primary key (id));
create table forma_pagamento (id int8 not null, descricao varchar(255) not null, primary key (id));
create table grupo (id int8 not null, nome varchar(255) not null, primary key (id));
create table grupo_has_permissao (grupo_id int8 not null, permissao_id int8 not null);
create table permissao (id int8 not null, descricao varchar(255), nome varchar(255) not null, primary key (id));
create table produto (id int8 not null, ativo boolean not null, descricao varchar(255), nome varchar(255) not null, preco numeric(19, 2) not null, restaurante_id int8, primary key (id));
create table restaurante (id int8 not null, created_at timestamp not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19, 2) not null, updated_at timestamp not null, cozinha_id int8 not null, endereco_cidade_id int8, primary key (id));
create table restaurante_has_forma_pagamento (restaurante_id int8 not null, forma_pagamento_id int8 not null);
create table usuario (id int8 not null, created_at timestamp not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, updated_at timestamp not null, primary key (id));
create table usuario_grupo (usuario_id int8 not null, grupo_id int8 not null);
alter table if exists cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado;
alter table if exists grupo_has_permissao add constraint FK4yy0qdocy8v7nslsu7lx1mmyk foreign key (permissao_id) references permissao;
alter table if exists grupo_has_permissao add constraint FKibwh6sgnrbw6nun3e13aoqygp foreign key (grupo_id) references grupo;
alter table if exists produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante;
alter table if exists restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha;
alter table if exists restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade;
alter table if exists restaurante_has_forma_pagamento add constraint FKh8mrqys0q1j1dw5jpankl6jn0 foreign key (forma_pagamento_id) references forma_pagamento;
alter table if exists restaurante_has_forma_pagamento add constraint FK3d8qb62mp0mi0rw16djsnspjg foreign key (restaurante_id) references restaurante;
alter table if exists usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo;
alter table if exists usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario;
create sequence cidade_id_seq start 1 increment 1;
create sequence cozinha_id_seq start 1 increment 1;
create sequence estado_id_seq start 1 increment 1;
create sequence forma_pagamento_id_seq start 1 increment 1;
create sequence grupo_id_seq start 1 increment 1;
create sequence permissao_id_seq start 1 increment 1;
create sequence produto_id_seq start 1 increment 1;
create sequence restaurante_id_seq start 1 increment 1;
create table cidade (id int8 not null, nome varchar(255) not null, estado_id int8 not null, primary key (id));
create table cozinha (id int8 not null, nome varchar(255) not null, primary key (id));
create table estado (id int8 not null, nome varchar(255) not null, sigla varchar(255) not null, primary key (id));
create table forma_pagamento (id int8 not null, descricao varchar(255) not null, primary key (id));
create table grupo (id int8 not null, nome varchar(255) not null, primary key (id));
create table grupo_has_permissao (grupo_id int8 not null, permissao_id int8 not null);
create table permissao (id int8 not null, descricao varchar(255), nome varchar(255) not null, primary key (id));
create table produto (id int8 not null, ativo boolean not null, descricao varchar(255), nome varchar(255) not null, preco numeric(19, 2) not null, restaurante_id int8, primary key (id));
create table restaurante (id int8 not null, created_at timestamp not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19, 2) not null, updated_at timestamp not null, cozinha_id int8 not null, endereco_cidade_id int8, primary key (id));
create table restaurante_has_forma_pagamento (restaurante_id int8 not null, forma_pagamento_id int8 not null);
create table usuario (id int8 not null, created_at timestamp not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, updated_at timestamp not null, primary key (id));
create table usuario_grupo (usuario_id int8 not null, grupo_id int8 not null);
alter table if exists cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado;
alter table if exists grupo_has_permissao add constraint FK4yy0qdocy8v7nslsu7lx1mmyk foreign key (permissao_id) references permissao;
alter table if exists grupo_has_permissao add constraint FKibwh6sgnrbw6nun3e13aoqygp foreign key (grupo_id) references grupo;
alter table if exists produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante;
alter table if exists restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha;
alter table if exists restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade;
alter table if exists restaurante_has_forma_pagamento add constraint FKh8mrqys0q1j1dw5jpankl6jn0 foreign key (forma_pagamento_id) references forma_pagamento;
alter table if exists restaurante_has_forma_pagamento add constraint FK3d8qb62mp0mi0rw16djsnspjg foreign key (restaurante_id) references restaurante;
alter table if exists usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo;
alter table if exists usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario;
create sequence cidade_id_seq start 1 increment 1;
create sequence cozinha_id_seq start 1 increment 1;
create sequence estado_id_seq start 1 increment 1;
create sequence forma_pagamento_id_seq start 1 increment 1;
create sequence grupo_id_seq start 1 increment 1;
create sequence permissao_id_seq start 1 increment 1;
create sequence produto_id_seq start 1 increment 1;
create sequence restaurante_id_seq start 1 increment 1;
create table cidade (id int8 not null, nome varchar(255) not null, estado_id int8 not null, primary key (id));
create table cozinha (id int8 not null, nome varchar(255) not null, primary key (id));
create table estado (id int8 not null, nome varchar(255) not null, sigla varchar(255) not null, primary key (id));
create table forma_pagamento (id int8 not null, descricao varchar(255) not null, primary key (id));
create table grupo (id int8 not null, nome varchar(255) not null, primary key (id));
create table grupo_has_permissao (grupo_id int8 not null, permissao_id int8 not null);
create table permissao (id int8 not null, descricao varchar(255), nome varchar(255) not null, primary key (id));
create table produto (id int8 not null, ativo boolean not null, descricao varchar(255), nome varchar(255) not null, preco numeric(19, 2) not null, restaurante_id int8, primary key (id));
create table restaurante (id int8 not null, created_at timestamp not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete numeric(19, 2) not null, updated_at timestamp not null, cozinha_id int8 not null, endereco_cidade_id int8, primary key (id));
create table restaurante_has_forma_pagamento (restaurante_id int8 not null, forma_pagamento_id int8 not null);
create table usuario (id int8 not null, created_at timestamp not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, updated_at timestamp not null, primary key (id));
create table usuario_grupo (usuario_id int8 not null, grupo_id int8 not null);
alter table if exists cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado;
alter table if exists grupo_has_permissao add constraint FK4yy0qdocy8v7nslsu7lx1mmyk foreign key (permissao_id) references permissao;
alter table if exists grupo_has_permissao add constraint FKibwh6sgnrbw6nun3e13aoqygp foreign key (grupo_id) references grupo;
alter table if exists produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante;
alter table if exists restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha;
alter table if exists restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade;
alter table if exists restaurante_has_forma_pagamento add constraint FKh8mrqys0q1j1dw5jpankl6jn0 foreign key (forma_pagamento_id) references forma_pagamento;
alter table if exists restaurante_has_forma_pagamento add constraint FK3d8qb62mp0mi0rw16djsnspjg foreign key (restaurante_id) references restaurante;
alter table if exists usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo;
alter table if exists usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario;
