version: '3.3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "docker"
    ports:
      - "5432:5432"
    volumes:
      - /home/adriano/Development/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "adriano.nq@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "docker"
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge